# =============================================================================
# Ontologie par défaut - Extraction générique
# =============================================================================
# Cette ontologie est utilisée si aucune ontologie spécifique n'est spécifiée.
# Elle couvre les cas d'usage généraux.

name: default
version: "1.0"
description: |
  Ontologie générique pour l'extraction d'informations structurées.
  Adapté à la plupart des documents sans domaine spécifique.

# Instructions générales pour le LLM
context: |
  Tu es un expert en extraction d'information. Analyse le document et extrait
  les entités et relations importantes de manière structurée.

# =============================================================================
# Types d'entités à extraire
# =============================================================================
entity_types:
  - name: Person
    description: Personne physique (nom, prénom, fonction)
    examples:
      - "Jean Dupont"
      - "Marie Martin (DSI)"
      - "Le Directeur Général"

  - name: Organization
    description: Entreprise, institution, association
    examples:
      - "Cloud Temple SAS"
      - "ANSSI"
      - "Commission Européenne"

  - name: Location
    description: Lieu géographique (ville, pays, adresse)
    examples:
      - "Paris"
      - "92000 Nanterre"
      - "France"

  - name: Date
    description: Date précise ou période
    examples:
      - "1er janvier 2026"
      - "Q1 2026"
      - "Mars 2025"

  - name: Concept
    description: Idée abstraite, terme métier
    examples:
      - "Transformation digitale"
      - "Gouvernance"
      - "Conformité"

  - name: Product
    description: Produit, logiciel, technologie
    examples:
      - "Microsoft Azure"
      - "VMware vSphere"
      - "Neo4j"

  - name: Document
    description: Référence à un autre document
    examples:
      - "Contrat Cadre"
      - "Annexe 1"
      - "Procès-verbal du CA"

  - name: Metric
    description: Valeur numérique, pourcentage, indicateur
    examples:
      - "99.95%"
      - "SLA 99.9%"
      - "Disponibilité 100%"

  - name: Duration
    description: Durée, délai, période
    examples:
      - "36 mois"
      - "3 ans"
      - "préavis 6 mois"

  - name: Amount
    description: Montant financier, tarif
    examples:
      - "50 000 EUR"
      - "2 500 EUR HT/mois"
      - "10% de pénalité"

# =============================================================================
# Types de relations entre entités
# =============================================================================
relation_types:
  - name: RELATED_TO
    description: Relation générique entre deux entités
    examples:
      - "Cloud Temple → RELATED_TO → SecNumCloud"

  - name: MENTIONS
    description: Le document mentionne une entité
    examples:
      - "Document → MENTIONS → Christophe Lesur"

  - name: BELONGS_TO
    description: Appartenance, affiliation
    examples:
      - "Jean Dupont → BELONGS_TO → Cloud Temple"

  - name: CREATED_BY
    description: Auteur, créateur
    examples:
      - "Rapport → CREATED_BY → Direction Technique"

  - name: REFERENCES
    description: Référence à un autre élément
    examples:
      - "Contrat → REFERENCES → Annexe 1"

  - name: DEFINES
    description: Définit ou spécifie une valeur
    examples:
      - "Article 5 → DEFINES → Durée 36 mois"

  - name: HAS_VALUE
    description: Associe une métrique à un concept
    examples:
      - "Disponibilité → HAS_VALUE → 99.95%"

# =============================================================================
# Règles d'extraction spécifiques
# =============================================================================
extraction_rules:
  max_entities: 30
  max_relations: 40
  include_metrics: true
  include_durations: true
  include_amounts: true
  extract_implicit_relations: false

# =============================================================================
# Exemples de documents et extractions attendues
# =============================================================================
examples:
  - input: |
      Le contrat est signé par Jean Dupont, DG de Cloud Temple SAS,
      pour une durée de 36 mois renouvelable.
    expected_entities:
      - {name: "Jean Dupont", type: "Person", description: "DG de Cloud Temple SAS"}
      - {name: "Cloud Temple SAS", type: "Organization"}
      - {name: "Durée 36 mois", type: "Duration", description: "Durée initiale du contrat"}
    expected_relations:
      - {from: "Jean Dupont", to: "Cloud Temple SAS", type: "BELONGS_TO"}
